version: '3'

services:
### PHP-FPM ##############################################
    php-fpm:
      image: teclaelvis01/php-fpm:7.3.12-xdebug-3.1.2
      build:
        context: ./php-fpm-7.3
        args:
          - INSTALL_XDEBUG=true
          - INSTALL_GMP=true
          - INSTALL_PHALCON=true
          - PHALCON_VERSION=3.4.5
      volumes:
        - ./php-fpm/php7.2.ini:/usr/local/etc/php/php.ini
        - ../:/var/www:cached
      expose:
        - "9000"
### NGINX Server #########################################
    nginx:
      image: teclaelvis01/nginx:0.0.1
      volumes:
        - ../:/var/www:cached
        - ./logs/nginx:/var/log/nginx
        - ./nginx/sites/:/etc/nginx/sites-available
        - ./nginx/ssl/:/etc/nginx/ssl
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - php-fpm

### MariaDB ##############################################
    mariadb:
      image: teclaelvis01/mariadb:10
      volumes:
        - ./datadb/mariadb:/var/lib/mysql
        - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      ports:
        - "3306:3306"
      environment:
        - TZ=UTC
        - MYSQL_DATABASE=default
        - MYSQL_USER=default
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=root
